### ISSUE TITLE
Add copy button in the export tabs

### ISSUE THREAD

**Issue by apresmoi** [Leniolabs/layoutit-tokens#19]
Remove the "user-select: all" that we currently have in the export/code section of the app and add a discrete "Copy" button on the top of each tab.

Pressing this copy button should copy the content of the current tab to the clipboard.

**Comment by adolfogustavo** [comment]
Can I work on this one? @apresmoi

**Comment by apresmoi** [comment]
Sure I have assigned it to you

**Comment by adolfogustavo** [comment]
I have sent a PR for this issue https://github.com/Leniolabs/layoutit-tokens/pull/23/files
@apresmoi

**Comment by apresmoi** [comment]
Merged ! Thank you
