### ISSUE TITLE
Refactor: variables and use already present libs

### ISSUE THREAD

**Issue by tadeork** [Leniolabs/layoutit-tokens#32]
Hello Layoutit team!
I'm thinking that could be a good idea to make some minors improvements like:

- Change all the ``var`` to ``const``.
- Move the function ``downloadZip`` in the ``index.vue`` file to a new separeted file.
- Use the ``cloneDeep`` from lodash lib instead of ``JSON.parse(JSON.stringify(this.sets[this.selectedToken]))``

**Comment by tadeork** [comment]
I just created a PR for this issue #33

**Comment by apresmoi** [comment]
Hi @tadeork, nice PR, thank you!

Just one minor change, instead of using `lodash.cloneDeep` could we use **[klona](https://github.com/lukeed/klona)**?

**Comment by tadeork** [comment]
Sure thing! Done.

**Comment by apresmoi** [comment]
I have merged the PR, thank you.
