### ISSUE TITLE
Improvement: remove lodash lib

### ISSUE THREAD

**Issue by tadeork** [Leniolabs/layoutit-tokens#34]
It could be a good idea to remove a library from which it's only used one method. In this case lodash lib is being used just for one method and almost the same case.
![image](https://user-images.githubusercontent.com/5428168/210894184-5f8dddfd-a2e7-499c-9de0-36ff6bb61018.png)

This ``_.set(...)`` method could be replaced with a custom function.

**Comment by apresmoi** [comment]
Merged, thank you!
